MovieBlend/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MovieBlend.Models;
using MovieBlend.Services;
namespace MovieBlend.Controllers
{
    public class PostController : Controller
    {
        private readonly IDiscussionDataService discussionDataService;
        private readonly UserManager<IdentityUser> _usermanger;
        public static string moviename;
        public static DIscussionModelArray DMA = new DIscussionModelArray();
        public static int movie_id;
        public PostController(IDiscussionDataService discussionData,UserManager<IdentityUser>userManager)
        {
            _usermanger = userManager;
            discussionDataService = discussionData;
        }
        public async Task<IActionResult> Index()
        {
            DMA.Data=await discussionDataService.GetDataAsync();
            DMA.MovieName = "Welcome";
            return View("Index",DMA);
        }
        public async Task<IActionResult> MediaDisCussion(string data)
        {
            int idm = to_int(data);
            movie_id = idm;
            Console.WriteLine(idm);
            DMA.Data =await discussionDataService.GetDataForMovie(idm);
            DMA.MovieName = moviename;
            return View("Index", DMA);
            DMA.MovieId = movie_id;
        }
        public IActionResult fill_form(string data)
        {
            int idm = to_int(data);
            movie_id = idm;
            return View("AddDiscussion");
        }
        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddDiscussion(DiscussionModel dummyData)
        {
            dummyData.Id = Guid.NewGuid();
            dummyData.Movie_ID = movie_id;
            dummyData.Movie_name = moviename;
            var currentUser = await _usermanger.GetUserAsync(User);
            if (currentUser == null)
            {
                return Challenge();
            }
            dummyData.Poster_ID = currentUser.Id;
            dummyData.poster_name = currentUser.UserName;
            var res=await discussionDataService.AddDiscussion(dummyData);
            return await DetailDiscussion(dummyData.Id.ToString());
         
        }
        public async Task<IActionResult> DeleteDiscussion(string data)
        {
            var xx = await discussionDataService.GetDataByidAsync(data);
            var res = await discussionDataService.DeleteData(xx);
            return await Index();
            
        }
        public async Task<IActionResult> DetailDiscussion(string idd)
        {
            DiscussionModel discussionModel = await discussionDataService.GetDataByidAsync(idd);
            return View("DetailDiscussion", discussionModel);
        }
        [Authorize]
        public async Task<IActionResult> get_my_data()
        {
            var currentUser = await _usermanger.GetUserAsync(User);
            if (currentUser == null)
            {
                return Challenge();
            }
            DMA.Data = await discussionDataService.MyDiscussion(currentUser.Id);
            DMA.MovieName = "Welcome";
            return View("Index", DMA);
            
        }
        public int to_int(string s)
        {
            int ans = 0;
            int j = 0;
            for (int i = 0; i < s.Length; i++)
            {
                j = i;
                if (Char.IsDigit(s[i]))
                    ans = ans * 10 + s[i] - '0';
                else break;
            }
            moviename = "";
            while (j < s.Length)
            {
                moviename += s[j];
                j++;
            }
            return ans;
        }

    }
}

MovieBlend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieBlend</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
    <!-- Bootstrap core CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="~/css/mdb.min.css" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body class="morpheus-den-gradient">
    <div id="fb-root"></div>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.3"></script>
    <div id="fb-root"></div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="logo container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://www.themoviedb.org/assets/2/v4/logos/primary-green-d70eebe18a5eb5b166d5c1ef0796715b8d1a2cbc698f96d311d62f894ae87085.svg" alt="The Movie Database (TMDb)" width="81" height="72">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-capitalize text-success" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link text-success text-capitalize dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true">Movies</a>
                            <div style="background-color:#343a40" class="dropdown-menu" aria-labelledby="navbardropdown">
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="PopularMovie">Popular</a>
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="Top_Movie"> Top Rated</a>
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="Upcoming">Upcoming</a>
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="Now_Playing">Now Playing</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link text-success text-capitalize dropdown-toggle" role="button" data-toggle="dropdown" aria-expanded="false" aria-haspopup="true">TV Shows</a>
                            <div style="background-color:#343a40" class="dropdown-menu" aria-labelledby="navbardropdown">
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="PopularTV">Popular</a>
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="Top_TV"> Top Rated</a>
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="ON_TV">ON TV</a>
                                <a class="dropdown-item text-success" asp-controller="Home" asp-area="" asp-action="Airing_today">Airing Today</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-success text-capitalize" asp-area="" asp-controller="Post" asp-action="Index">Forum</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container inner_content">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - MovieBlend - <a asp-area="" asp-controller="Home" asp-action="Privacy">Developer</a>
        </div>
    </footer>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>